<a class="skip-link" href="#main">انتقلي للمحتوى</a>
<?php if (get_theme_mod('karma_announcement_enabled', true)) : ?><div class="announcement" role="region" aria-label="أخبار و<?php echo esc_html(get_theme_mod('karma_announcement', 'عروض كارما')); ?>"><div class="announcement-track"><div class="announcement-group" dir="rtl"><span><?php echo esc_html(get_theme_mod('karma_announcement', 'عروض كارما')); ?></span><span class="offer-dot" aria-hidden="true">•</span><span>هدية عيّنة عناية مع أول طلب</span><span class="offer-dot" aria-hidden="true">•</span><span>خصم 10% بعد التسجيل</span><span class="offer-dot" aria-hidden="true">•</span><span>كود الترحيب KARMA10</span><span class="offer-dot" aria-hidden="true">•</span><span>التوصيل للقاهرة 50 ج.م. وباقي المحافظات 120 ج.م.</span><span class="offer-dot" aria-hidden="true">•</span><span>انضمي لكارما واكتشفي مفضّلاتك</span><span class="offer-dot" aria-hidden="true">•</span></div><div class="announcement-group" dir="rtl" aria-hidden="true"><span><?php echo esc_html(get_theme_mod('karma_announcement', 'عروض كارما')); ?></span><span class="offer-dot" aria-hidden="true">•</span><span>هدية عيّنة عناية مع أول طلب</span><span class="offer-dot" aria-hidden="true">•</span><span>خصم 10% بعد التسجيل</span><span class="offer-dot" aria-hidden="true">•</span><span>كود الترحيب KARMA10</span><span class="offer-dot" aria-hidden="true">•</span><span>التوصيل للقاهرة 50 ج.م. وباقي المحافظات 120 ج.م.</span><span class="offer-dot" aria-hidden="true">•</span><span>انضمي لكارما واكتشفي مفضّلاتك</span><span class="offer-dot" aria-hidden="true">•</span></div></div><button class="announcement-close" type="button" data-dismiss-announcement aria-label="إغلاق شريط العروض"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="m7 7 10 10M17 7 7 17"/></svg></button></div>
<?php endif; ?><header class="site-header">
  <div class="header-main wrap">
    <div class="header-tools"><button class="icon-button account-button" data-action="account" aria-label="حسابي والتسجيل"><i data-icon="user"></i></button><button class="icon-button" data-action="cart" aria-label="افتحي حقيبة التسوق"><i data-icon="bag"></i><span class="cart-count" data-cart-count>0</span></button><button class="icon-button favorites-button" data-action="favorites" aria-label="منتجاتك المفضلة"><i data-icon="heart"></i></button><button class="icon-button mobile-menu" data-action="menu" aria-label="افتحي القائمة الجانبية" aria-controls="menu-dialog" aria-expanded="false"><i data-icon="menu"></i></button></div>
    <a class="brand" data-link="home" href="./" aria-label="Karma Beauty الرئيسية"><img src="<?php echo esc_url(get_template_directory_uri()); ?>/assets/logo.svg" width="145" height="64" alt="karma beauty"></a>
    <div class="header-actions"><button class="language-switch" type="button" data-language-toggle data-no-translate lang="ar" aria-label="Switch to Arabic">ع</button><button class="search-trigger" data-action="search" aria-label="البحث عن المنتجات"><i data-icon="search"></i><span>بتدوري على إيه؟</span></button></div>
  </div>
  <nav class="main-nav" aria-label="القائمة الرئيسية"><a data-link="shop" href="#shop">كل المنتجات</a><a data-category-link="skin" href="#shop">العناية بالبشرة</a><a data-category-link="makeup" href="#shop">المكياج</a><a data-category-link="hair" href="#shop">العناية بالشعر</a><a data-category-link="body" href="#shop">الجسم والاستحمام</a><a href="#about" data-home-anchor="about">عن كارما</a><a href="#contact" data-home-anchor="contact">اتصل بنا</a></nav>
</header>
