import {chromium} from '@playwright/test';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1024},deviceScaleFactor:1});
await page.emulateMedia({reducedMotion:'reduce'});
await page.mouse.move(0,0);
await page.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});
await page.locator('.payment-section').scrollIntoViewIfNeeded();
await page.locator('img').evaluateAll(async imgs=>Promise.all(imgs.map(i=>{i.loading='eager';return i.decode();})));
await page.evaluate(()=>window.scrollTo(0,0));
await page.screenshot({animations:'disabled',path:'qa/desktop-first-screen.png'});
await page.screenshot({animations:'disabled',path:'qa/desktop.png',fullPage:true});
await page.locator('.site-footer').scrollIntoViewIfNeeded();
await page.waitForFunction(()=>document.body.classList.contains('footer-in-view'));
await page.locator('.site-footer').screenshot({path:'qa/footer.png',animations:'disabled'});
await page.locator('#contact').screenshot({path:'qa/contact.png'});
await page.locator('.payment-section').screenshot({path:'qa/payments.png'});
await page.evaluate(()=>window.scrollTo(0,0));
await page.locator('[data-action="menu"]').click();
await page.mouse.move(0,0);
await page.screenshot({animations:'disabled',path:'qa/sidebar.png',animations:'disabled'});
await page.keyboard.press('Escape');
await page.setViewportSize({width:390,height:844});
await page.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});
await page.locator('.payment-section').scrollIntoViewIfNeeded();
await page.locator('img').evaluateAll(async imgs=>Promise.all(imgs.map(i=>{i.loading='eager';return i.decode();})));
await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0);});
await page.screenshot({animations:'disabled',path:'qa/mobile-first-screen.png'});
await page.screenshot({animations:'disabled',path:'qa/mobile.png',fullPage:true});
await page.locator('[data-action="menu"]').click();
await page.mouse.move(0,0);
await page.screenshot({animations:'disabled',path:'qa/mobile-sidebar.png',animations:'disabled'});
await page.setViewportSize({width:734,height:668});
await page.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});
await page.screenshot({path:'qa/tablet-first-screen.png',animations:'disabled'});
await page.locator('.site-footer').scrollIntoViewIfNeeded();
await page.waitForFunction(()=>document.body.classList.contains('footer-in-view'));
await page.locator('.site-footer').screenshot({path:'qa/tablet-footer.png',animations:'disabled'});
await page.setViewportSize({width:1440,height:1000});
await page.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});
await page.locator('[data-action="show-all"]').click();
await page.locator('.product-picture img').evaluateAll(async imgs=>Promise.all(imgs.map(i=>{i.loading='eager';return i.decode();})));
await page.locator('#product-grid').screenshot({path:'qa/products-all.png',animations:'disabled'});
await page.locator('[data-add="1"]').click();
await page.locator('.header-tools [data-action="account"]').click();
await page.locator('[data-action="sample-member"]').click();
await page.locator('#member-dialog').screenshot({path:'qa/member-desktop.png',animations:'disabled'});
await page.locator('[data-action="use-coupon"]').click();
await page.locator('#shipping-governorate').selectOption('القاهرة');
await page.locator('#cart-dialog').screenshot({path:'qa/cart-discount.png',animations:'disabled'});
console.log('Captured clean desktop, mobile, sidebar, contact, and payment previews.');
await browser.close();
