import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:595,height:668}});
const errors=[],writes=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('request',r=>{if(r.method()!=='GET')writes.push(r.url());});
await page.addInitScript(()=>localStorage.setItem('karma-language','ar'));
await page.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'});
assert.deepEqual(await page.locator('.product-picture').evaluateAll(es=>es.map(e=>Number(e.dataset.product))),[1,14,17,11,5,15,18,20]);
await page.locator('#load-more').click();
await expect(page.locator('.product-card')).toHaveCount(16);
await page.locator('#load-more').click();
await expect(page.locator('.product-card')).toHaveCount(20);
await expect(page.locator('#load-more')).toBeHidden();
assert.equal((await page.locator('.announcement').innerText()).includes('مجاني'),false);
await expect(page.locator('.brand-ribbon')).toHaveCount(0);
await expect(page.locator('.ritual-image .image-note')).toHaveCount(0);
await expect(page.locator('.ritual-image img')).toHaveAttribute('src',/ritual-printed.webp/);
// A full ticker cycle must always cover the viewport; RTL must not start it off-screen.
assert.equal(await page.locator('.announcement-track').evaluate(e=>{const animation=e.getAnimations()[0],original=animation.currentTime,duration=animation.effect.getTiming().duration;let covers=true;for(const portion of [0,.25,.5,.75,.999]){animation.currentTime=duration*portion;const r=e.getBoundingClientRect();covers&&=r.left<=1&&r.right>=innerWidth-1;}animation.currentTime=original;return covers;}),true);
await page.locator('[data-action="search"]').click();
await expect(page.locator('.search-product')).toHaveCount(6);
await page.locator('#search-results img').evaluateAll(async imgs=>Promise.all(imgs.map(i=>i.decode())));
await page.locator('#search-dialog').screenshot({path:'qa/search-suggestions.png',animations:'disabled'});
await page.locator('#search-input').fill('نايت');
await expect(page.locator('.search-product')).toHaveCount(1);
await expect(page.locator('.search-product img')).toHaveAttribute('src',/night-dew/);
await page.locator('#search-dialog').screenshot({path:'qa/search-filtered.png',animations:'disabled'});
await page.locator('#search-input').fill('xyz');
await expect(page.locator('.search-empty')).toBeVisible();
await page.locator('#search-input').fill('');
await expect(page.locator('.search-product')).toHaveCount(6);
await page.locator('.search-product').first().click();
await expect(page.locator('#product-dialog')).toBeVisible();
await page.keyboard.press('Escape');
await page.locator('[data-add="1"]').click();
await page.locator('[data-action="cart"]').click();
await page.locator('[data-action="checkout"]').click();
await expect(page.locator('#shipping-error')).toContainText('اختاري');
await expect(page.locator('#info-dialog')).not.toBeVisible();
await page.locator('#shipping-governorate').selectOption('القاهرة');
await expect(page.locator('[data-shipping]')).toContainText('٥٠');
await expect(page.locator('[data-grand-total]')).toContainText('٥٣٥');
await page.locator('#shipping-governorate').selectOption('الجيزة');
await expect(page.locator('[data-shipping]')).toContainText('١٢٠');
await expect(page.locator('[data-grand-total]')).toContainText('٦٠٥');
for(const method of ['visa','mastercard','fawry','paymob']){
 await page.locator('input[name="payment"][value="'+method+'"]').check();
 await expect(page.locator('input[name="payment"]:checked')).toHaveCount(1);
 await expect(page.locator('input[name="payment"][value="'+method+'"]')).toBeChecked();
 await page.locator('.payment-choice img').evaluateAll(async imgs=>Promise.all(imgs.map(i=>i.decode())));
 await expect(page.locator('.payment-coming')).toContainText(method==='fawry'?'فوري':method==='visa'?'Visa':method==='mastercard'?'Mastercard':'Paymob');
}
await expect(page.locator('.payment-coming')).toContainText('هيتوفر لاحقًا');
await page.locator('[data-action="checkout"]').click();
await expect(page.locator('#info-dialog')).not.toBeVisible();
await page.locator('[data-action="choose-cod"]').click();
await expect(page.locator('input[value="cod"]')).toBeChecked();
await expect(page.locator('.payment-coming')).toHaveCount(0);
assert.equal((await page.locator('#cart-content').innerText()).includes('تجريب'),false);
await page.locator('#delivery-address').fill('شارع النيل، عمارة 12، الدور 3، شقة 8، بجوار الصيدلية');
await page.locator('#contact-phone').fill('01012345678');
await page.locator('[data-action="checkout"]').click();
await expect(page.locator('#info-content')).toContainText('الجيزة');
await expect(page.locator('#info-content')).toContainText('٦٠٥');
await expect(page.locator('#info-content')).toContainText('مفيش طلب اتبعت');
await page.locator('[data-action="back-cart"]').click();
await page.reload({waitUntil:'networkidle'});
await page.locator('[data-action="cart"]').click();
await expect(page.locator('#shipping-governorate')).toHaveValue('الجيزة');
await page.locator('#shipping-governorate').selectOption('القاهرة');
await page.locator('#cart-dialog').screenshot({path:'qa/cart-delivery.png',animations:'disabled'});
await page.keyboard.press('Escape');
await page.locator('.category-card img').evaluateAll(async imgs=>Promise.all(imgs.map(i=>{i.loading='eager';return i.decode();})));
assert.equal(await page.locator('.ritual-sign').evaluate(e=>getComputedStyle(e).transform),'none');
await page.setViewportSize({width:1440,height:1000});
await page.evaluate(()=>document.activeElement?.blur());
await page.locator('.category-section').screenshot({path:'qa/comment-categories-desktop.png',animations:'disabled'});
await page.setViewportSize({width:488,height:850});
await page.locator('.category-section').screenshot({path:'qa/comment-categories-mobile.png',animations:'disabled'});
await page.locator('.ritual-copy').screenshot({path:'qa/comment-signature.png',animations:'disabled'});
await page.locator('[data-action="cart"]').click();
await page.locator('.payment-choice').screenshot({path:'qa/comment-payment-choices.png',animations:'disabled'});
await page.keyboard.press('Escape');
for(const width of [320,390,595,680,734,1440]){
 await page.setViewportSize({width,height:850});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Page overflow '+width);
 const sizes=await page.locator('.floating-contact a').evaluateAll(es=>es.map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));
 assert.deepEqual(sizes[0],sizes[1]);assert.equal(sizes[0].w,sizes[0].h);
 await page.locator('[data-action="search"]').click();
 assert.equal(await page.locator('#search-dialog').evaluate(e=>e.scrollWidth>e.clientWidth),false,'Search overflow '+width);
 await page.keyboard.press('Escape');
 await page.locator('[data-action="cart"]').click();
 assert.equal(await page.locator('#cart-dialog').evaluate(e=>e.scrollWidth>e.clientWidth),false,'Cart overflow '+width);
 await page.keyboard.press('Escape');
}
assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);
await fs.writeFile('qa/v16-results.json',JSON.stringify({passed:true,checks:['8 curated products then 16 then 20','decorative ribbon removed','ritual inscription embedded in image','ticker coverage full cycle','live image search and empty query recovery','Cairo 50, Giza 120','governorate required and persisted','individual branded payment choices with explicit COD fallback','no order or payment sent','matching round contact buttons','responsive dialogs at 320/390/595/680/734/1440'],errors,writes},null,2));
await browser.close();
console.log('PASS: v1.6 catalog, ribbons, search, delivery, payment choice and responsive dialogs.');
