import {chromium,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const catalog=JSON.parse(await fs.readFile('assets/products.json','utf8'));
assert.equal(new Set(catalog.map(p=>p.image)).size,20,'Each product needs a distinct image reference');
const imageHashes=await Promise.all(catalog.map(async p=>createHash('sha256').update(await fs.readFile(`assets/${p.image}.webp`)).digest('hex')));
assert.equal(new Set(imageHashes).size,20,'Product image files must be distinct');
await fs.mkdir('qa',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];const failed=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.status()>=400)failed.push(`${r.status()} ${r.url()}`)});
await page.addInitScript(()=>localStorage.setItem('karma-language','ar'));
await page.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});
await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:'qa/desktop.png',fullPage:true});
assert.equal(await page.locator('.product-card').count(),12);
await page.locator('[data-filter="hair"]').click();
assert.equal(await page.locator('.product-card').count(),4);
assert.match(await page.locator('#product-grid').innerText(),/الشعر/);
await page.locator('[data-action="show-all"]').click();
assert.equal(await page.locator('.product-card').count(),20);
await page.locator('.product-picture img').evaluateAll(async imgs=>Promise.all(imgs.map(i=>{i.loading='eager';return i.decode();})));
assert.equal(await page.locator('#load-more').isVisible(),false);
await page.locator('#sort').selectOption('low');
assert.match(await page.locator('.product-card').first().innerText(),/روز تاتش/);
await page.locator('[data-action="search"]').click();
await page.locator('#search-input').fill('روز كيس');
await page.locator('#search-form').evaluate(f=>f.requestSubmit());
assert.equal(await page.locator('.product-card').count(),1);
await page.locator('[data-favorite="2"]').click();
await page.locator('[data-action="favorites"]').first().click();
assert.equal(await page.locator('.product-card').count(),1);
await page.locator('[data-product="2"]').first().click();
await page.locator('input[name="shade"][value="موف"]').check();
await page.locator('#detail-qty').fill('2');
await page.locator('[data-detail-add="2"]').click();
assert.equal(await page.locator('.header-tools [data-cart-count]').innerText(),'2');
await page.locator('[data-action="cart"]').click();
assert.match(await page.locator('#cart-content').innerText(),/موف/);
await page.locator('[data-cart-qty="1"]').click();
assert.equal(await page.locator('.header-tools [data-cart-count]').innerText(),'3');
await page.locator('#cart-dialog [data-close]').click();
await page.reload({waitUntil:'networkidle'});
assert.equal(await page.locator('.header-tools [data-cart-count]').innerText(),'3');
await page.locator('[data-action="cart"]').click();
await page.screenshot({path:'qa/cart.png'});
await page.locator('#shipping-governorate').selectOption('القاهرة');
await page.locator('#delivery-address').fill('شارع النيل، عمارة 12، الدور 3، شقة 8، بجوار الصيدلية');
await page.locator('#contact-phone').fill('01012345678');
await page.locator('[data-action="checkout"]').click();
assert.match(await page.locator('#info-content').innerText(),/مفيش طلب اتبعت/);
await page.locator('#info-dialog [data-close]').click();
await page.locator('[data-action="search"]').click();
await page.locator('#search-input').fill('zzzz-no-product');
await page.locator('#search-form').evaluate(f=>f.requestSubmit());
assert.match(await page.locator('#product-grid').innerText(),/مفيش نتائج/);
await page.locator('.empty-products [data-action="reset"]').click();
for(const width of [320,390,595,734,768,1440]){
 await page.setViewportSize({width,height:900});await page.reload({waitUntil:'networkidle'});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 assert.equal(overflow,false,`Horizontal overflow at ${width}px`);
 const pill=await page.locator('.quick-add').first().evaluate(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,parent:e.parentElement.getBoundingClientRect().width}));
 assert.ok(pill.height<=38&&pill.width<pill.parent-12,`Compact product action at ${width}px`);
 const images=await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>i.complete&&i.naturalWidth===0).map(i=>i.src));
 assert.deepEqual(images,[]);
 if(width===390){
  await page.screenshot({path:'qa/mobile.png',fullPage:true});
  await page.locator('[data-action="menu"]').click();
  assert.equal(await page.locator('#menu-dialog').isVisible(),true);
  await page.locator('#menu-dialog [data-category-link="makeup"]').click();
  assert.equal(await page.locator('.product-card').count(),5);
  assert.equal(await page.locator('#menu-dialog').isVisible(),false);
 }
}
await page.locator('[data-action="menu"]').click();
assert.equal(await page.locator('[data-action="menu"]').getAttribute('aria-expanded'),'true');
await page.keyboard.press('Escape');
assert.equal(await page.locator('#menu-dialog').isVisible(),false);
await expect(page.locator('[data-action="menu"]')).toHaveAttribute('aria-expanded','false');
await page.locator('[data-action="menu"]').click();
await page.locator('#menu-dialog [data-home-anchor="contact"]').click();
assert.equal(await page.locator('#menu-dialog').isVisible(),false);
for(const link of await page.locator('[data-contact="whatsapp"]').all()) await expect(link).toHaveAttribute('href','https://wa.me/201018239900');
for(const link of await page.locator('[data-contact="phone"]').all()) await expect(link).toHaveAttribute('href','tel:+201018239900');
for(const link of await page.locator('[data-contact="email"]').all()) await expect(link).toBeHidden();
for(const note of await page.locator('[data-contact-demo]').all()) await expect(note).toBeHidden();
assert.notEqual(await page.locator('.hero-image').getAttribute('src'),await page.locator('.ritual-image img').getAttribute('src'));
assert.equal(await page.locator('.hero-seal,.art-spark,[data-action="hero-motion"]').count(),0);
assert.equal(await page.locator('.hero-image').evaluate(e=>getComputedStyle(e).animationName),'none');
await page.mouse.move(0,0);
await expect.poll(()=>page.locator('.hero-image').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m11)).toBe(1);
await page.locator('.hero-art').hover();
await expect.poll(()=>page.locator('.hero-image').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m11)).toBe(1.06);
await page.mouse.move(0,0);
await expect.poll(()=>page.locator('.hero-image').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m11)).toBe(1);
await page.emulateMedia({reducedMotion:'reduce'});
assert.equal(await page.locator('.hero-image').evaluate(e=>getComputedStyle(e).animationName),'none');

assert.equal(await page.locator('.footer-wordmark').count(),0);
await expect(page.locator('.footer-signoff')).toContainText('كل يوم، لمسة جمال تشبهك.');
assert.equal(await page.locator('.announcement-group').count(),2);
await expect(page.locator('.announcement-group').nth(1)).toHaveAttribute('aria-hidden','true');
assert.equal(await page.locator('.announcement-group').first().innerText(),await page.locator('.announcement-group').nth(1).innerText());
const tickerStart=await page.locator('.announcement-track').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41);
await expect.poll(async()=>Math.abs(await page.locator('.announcement-track').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41)-tickerStart)).toBeGreaterThan(5);
await page.locator('.payment-section').scrollIntoViewIfNeeded();
await page.locator('.payment-logos img').evaluateAll(async imgs=>Promise.all(imgs.map(i=>i.decode())));
assert.equal(await page.locator('.payment-logos img').count(),4);
assert.equal(await page.locator('body').evaluate(e=>getComputedStyle(e).fontFamily.includes('Tajawal')),true);
assert.ok(await page.locator('.hero .button').evaluate(e=>e.getBoundingClientRect().height<45));
await page.locator('#contact').screenshot({path:'qa/contact.png'});
await page.locator('.payment-section').screenshot({path:'qa/payments.png'});
await page.locator('[data-action="menu"]').click();
await page.screenshot({path:'qa/sidebar.png'});
await page.keyboard.press('Escape');
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
await fs.writeFile('qa/results.json',JSON.stringify({passed:true,checks:['20 unique product images and hashes','compact product action buttons','20 products','category filters','price sorting','Arabic search','favorites','shade selection','cart quantities','cart persistence','demo checkout','empty search','mobile menu','real phone and WhatsApp link targets','missing email hidden','distinct hero and ritual images','continuous zoom changes scale','seamless offers ticker advances','readable footer signoff','hero badge, star and motion control removed','no horizontal overflow at 320/390/734/768/1440','images loaded','no JS exceptions','no failed HTTP responses'],errors,failed},null,2));
console.log('PASS: storefront interactions, persistence, responsive layout, asset loading, and console checks.');
await browser.close();

